name: MythicItemFinder
version: 1.0.0
main: net.azisaba.mythicitemfinder.MythicItemFinder
api-version: 1.13
depend:
  - MythicMobs
softdepend:
  - LifePvELevel
commands:
  mythicitemfinder:
    permission: mythicitemfinder.command
    aliases: ["mythicitemlist"]
